// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu_FXbaa4zsOWWvRI1KVok8D88-KM-0QY',
    appId: '1:890707683759:web:066c6720935521b7ba675a',
    messagingSenderId: '890707683759',
    projectId: 'th-flutter-d1366',
    authDomain: 'th-flutter-d1366.firebaseapp.com',
    databaseURL: 'https://th-flutter-d1366-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'th-flutter-d1366.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9c4eMWq0LgP84P0aF0iNn8qY1ngRWoh8',
    appId: '1:890707683759:android:c5dd2ac7851edaa3ba675a',
    messagingSenderId: '890707683759',
    projectId: 'th-flutter-d1366',
    databaseURL: 'https://th-flutter-d1366-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'th-flutter-d1366.appspot.com',
  );
}
